name: food_booking
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: 4.0.4
  loading: ^1.0.2
  flutter_spinkit: ^4.1.2+1
  badges: 1.1.0
  pin_code_text_field: ^1.5.0
  shared_preferences: any
  flutter_money_formatter: ^0.8.3
  image_picker: 0.6.2+3
  fluttertoast: 3.1.3
  flutter_icons:
  dio: ^3.0.8
  progress_dialog: 1.2.0
  pull_to_refresh: 1.5.7
  shimmer: 1.0.1
  pie_chart: 3.1.1
  html: ^0.14.0+3
  sticky_headers: 0.1.8+1
  cached_network_image: 2.0.0
  photo_view: 0.9.1
  device_info: any
  flutter_device_type: any
  package_info: any
  auto_size_text: 2.1.0
  solid_bottom_sheet: 0.1.9
#  cache_image: 1.0.5
  webview_flutter: 0.3.20+2
  image: ^2.1.14
  get:
  google_maps_flutter: 0.5.30
#  google_map_location_picker: 3.3.3
  geolocator: ^5.3.2+2
  location: ^3.0.0
  flutter_launcher_icons: ^0.7.3
  font_awesome_flutter: ^8.4.0
  country_pickers: ^1.1.0
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  division: ^0.6.1
  page_transition: '^1.1.0'
  bottom_navy_bar: ^5.1.0
  sliding_up_panel: ^0.3.4
  flutter_xlider: ^2.5.1
  intro_views_flutter: ^2.6.0
  rflutter_alert: ^1.0.3
  hidden_drawer_menu: ^1.1.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconapp.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/products.json
    - assets/data/categories.json
    - assets/images/banana.png
    - assets/images/kiwi.png
    - assets/images/orange.png
    - assets/images/apple.png
    - assets/images/watermelon.png
    - assets/images/strawberry.png
    - assets/images/peppers.png
    - assets/images/broccoli.png
    - assets/images/carrot.png
    - assets/images/logo_large.png
    - assets/images/logo.png
    - assets/images/icon_eye.png
    - assets/images/icon_eye_close.png
    - assets/images/icons/profile.png
    - assets/images/icons/profile_selected.png
    - assets/images/arrow_next.png
    - assets/images/logo_white.png
    - assets/images/logo_slogen.png
    - assets/images/logo_splash.png
    - assets/images/icon_down.png
    - assets/images/icon_mail.png
    - assets/images/icon_success.png
    - assets/images/icons/icon_tab_tuclass.png
    - assets/images/icons/icon_tab_tuclass_selected.png
    - assets/images/icon_class_active.png
    - assets/images/icon_class_unactive.png
    - assets/images/icon_class_active.png
    - assets/images/icons/icon_tab_exam.png
    - assets/images/icons/icon_tab_exam_selected.png
    - assets/images/icons/icon_tab_knowledge.png
    - assets/images/icons/icon_tab_knowledge_selected.png
    - assets/images/icons/icon_tab_statistics.png
    - assets/images/icons/icon_tab_statistics_selected.png
    - assets/images/icon_change.png
    - assets/images/icon_change_password.png
    - assets/images/icon_next.png
    - assets/images/icon_profile.png
    - assets/images/icon_time.png
    - assets/images/icon_back.png
    - assets/images/icon_biology.png
    - assets/images/icon_chemistry.png
    - assets/images/icon_english.png
    - assets/images/icon_ethics.png
    - assets/images/icon_geography.png
    - assets/images/icon_history.png
    - assets/images/icon_information.png
    - assets/images/icon_mathematics.png
    - assets/images/icon_physics.png
    - assets/images/icon_science.png
    - assets/images/icon_sociology.png
    - assets/images/icon_technology.png
    - assets/images/icon_vietnamese.png
    - assets/images/icon_exam_finished.png
    - assets/images/icon_exam_registered.png
    - assets/images/icon_advance_search.png
    - assets/images/icon_bookmark.png
    - assets/images/icon_back_exam.png
    - assets/images/icon_down_exam.png
    - assets/images/icon_radio_on.png
    - assets/images/icon_radio_off.png
    - assets/images/change_class.png
    - assets/images/bg_topup.png
    - assets/images/icon_back_exam_invisible.png
    - assets/images/icon_next_invisible.png
    - assets/images/icon_next_exam_visible.png
    - assets/images/icon_visa.png
    - assets/images/icon_atm.png
    - assets/images/icon_transaction_success.png
    - assets/images/menus/ic_search_menu.png
    - assets/images/menus/ic_account.png
    - assets/images/menus/ic_cart.png
    - assets/images/menus/ic_home.png
    - assets/images/menus/ic_delete.png
    - assets/images/menus/ic_near_by.png
    - assets/images/menus/ic_credit_card.png
    - assets/images/menus/ic_app_icon.png
    - assets/images/menus/ic_food_express.png
    - assets/images/menus/ic_app_icon_black.png
    - assets/images/topmenu/ic_burger.png
    - assets/images/topmenu/ic_cake.png
    - assets/images/topmenu/ic_ice_cream.png
    - assets/images/topmenu/ic_pasta.png
    - assets/images/topmenu/ic_pizza.png
    - assets/images/topmenu/ic_sushi.png
    - assets/images/topmenu/ic_soft_drink.png
    - assets/images/popular_foods/ic_popular_food_1.png
    - assets/images/popular_foods/ic_popular_food_2.png
    - assets/images/popular_foods/ic_popular_food_3.png
    - assets/images/popular_foods/ic_popular_food_4.png
    - assets/images/popular_foods/ic_popular_food_5.png
    - assets/images/popular_foods/ic_popular_food_6.png
    - assets/images/bestfood/ic_best_food_1.jpeg
    - assets/images/bestfood/ic_best_food_2.jpeg
    - assets/images/bestfood/ic_best_food_3.jpeg
    - assets/images/bestfood/ic_best_food_4.jpeg
    - assets/images/bestfood/ic_best_food_5.jpeg
    - assets/images/bestfood/ic_best_food_6.jpeg
    - assets/images/bestfood/ic_best_food_7.jpeg
    - assets/images/bestfood/ic_best_food_8.jpeg
    - assets/images/bestfood/ic_best_food_9.jpeg
    - assets/images/bestfood/ic_best_food_10.jpeg
    - assets/images/bag_1.png
    - assets/images/bag_2.png
    - assets/images/bag_3.png
    - assets/images/bag_4.png
    - assets/images/bag_5.png
    - assets/images/bag_6.png

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
